baseURL = "https://learningsoftware.netlify.app/"
languageCode = 'es-co'
title = 'Learning software blog'
theme = "m10c"
#paginate = 8

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "https://neyperea.me/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3

[params]
  author = "Ney Perea"
  description = "Tarde o temprano la Disciplina vencerá a la inteligencia"
  avatar = "images/avatar.png"
  # menu_item_separator = " - "
  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/nperea-dev"
  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://x.com/nperea_dev"

  # Default theme
  #[params.style]
  #  darkestColor = "#242930"
  #  darkColor = "#353b43"
  #  lightColor = "#afbac4"
  #  lightestColor = "#ffffff"
  #  primaryColor = "#57cc8a"

  #Green theme
[params.style]
 darkestColor = "#315659"
 darkColor = "#253031"
 lightColor = "#96a879"
 lightestColor = "#fff"
 primaryColor = "#dad865"

  # Red theme
 # [params.style]
 #  darkestColor = "#d35050"
 #  darkColor = "#212121"
 #  lightColor = "#d6d6d6"
 #  lightestColor = "#d3d3d3"
 #  primaryColor = "#ffffff"
  
 

# Set unsafe mode to allow markdownify to work with goldmark
# This is important. Please do not delete. It is used to re-render markdown
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
