baseURL: "https://neyperea.me"
languageCode: en-us
title: "Learning code"
theme: m10c


params:
  author: "nperea75Dev"
  avatar: "images/avatar.png"
  description: "la disciplina vencerá a la inteligencia."
